services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./api/orcirecords 
    container_name: orcirecords_api
    ports:
      - "8080:8080"  
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    command: ["java", "-jar", "/app.jar"]
  frontend:
    build:
      context: ./ui/orcirecords  
    container_name: orcirecords_ui
    ports:
      - "80:80"  
    depends_on:
      - db
      - backend

volumes:
  postgres_data:
